config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [:create, :new]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORIES}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: [0,1,2,3,4,5]}, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
  class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @reviews =@restaurant.reviews.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurants_path
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end



  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category, :rating, :pictureurl)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    # we need `restaurant_id` to asssociate review with corresponding restaurant
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    if @review.save
      redirect_to restaurant_path(@review.restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-8 offset-md-2">
      <h1> Edit Restaurant </h1>
      <hr>
      <%= simple_form_for(@restaurant) do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :phone_number %>
        <%= f.input :category %>
        <%= f.submit "Edit restaurant", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="home-banner">
  <h1>Restomappers</h1>
</div>
<div class="container main-list">
  <% @restaurants.each do |restaurant| %>
    <div class="row">
      <div class="col-xs-12 col-md-8 offset-md-3 card">
        <div class="upvote">
          <% [1,2,3,4,5].sample.times do %>
            <i class="fas fa-star"></i>
          <% end %>
        </div>
        <img class= "picture" src=<%= restaurant.pictureurl %>>
        <div class="info">
          <h2><%=  link_to restaurant.name, restaurant_path(restaurant.id) %></h2>
          <p><%= restaurant.category.capitalize %> - <%= restaurant.address %></p>
        </div>
        <div class="delete">
          <%= link_to restaurant_path(restaurant.id),
          method: :delete,
          data: { confirm: "Are you sure?"} do %>
            <i class="fa fa-trash" aria-hidden="true"></i>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-8 offset-md-3">
      <h1>Create a new restaurant</h1>
      <%= simple_form_for(@restaurant) do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :phone_number %>
        <%= f.input :category %>
        <%= f.submit "Add restaurant", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <%= link_to 'Edit this restaurant',  edit_restaurant_path, class: 'btn btn-primary btn-edit' %>
    <div class="col-md-6 col-md-offset-3">
      <div class="editor">
        <h1><%= @restaurant.name %></h1>
        <img class= "picture center-block" src=<%= @restaurant.pictureurl %>>
      </div>
      <div class="desc">
        <p>Category: <%= @restaurant.category.capitalize %></p>
        <p><%= @restaurant.address %></p>
        <p><%= @restaurant.phone_number %></p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4 col-md-offset-4"">
      <hr>
      <p><%= link_to 'Write a review', new_restaurant_review_path(@restaurant) %> / <%= link_to 'Back to list', restaurants_path %></p>
    </div>
  </div>
  <div class="row">
    <% unless @reviews.empty? %>
      <div class="col-md-4 col-md-offset-4"">
        <h2>Reviews</h2>
        <hr>
        <% @reviews.each do |review|%>
          <p>
            <%= review.rating %><i class="fas fa-star"></i>
            <%= review.content %>
          </p>
          <hr>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-8 offset-md-3">
      <h1>Create a new review</h1>
      <%= simple_form_for [@restaurant, @review] do |f| %>
        <%= f.input :content %>
        <%= f.input :rating %>
        <%= f.submit "Add review", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Links -->
    <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>